# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install libgeos
        run: |
          # Temporary? dpkg fix: https://askubuntu.com/questions/1276111/error-upgrading-grub-efi-amd64-signed-special-device-old-ssd-does-not-exist
          sudo rm /var/cache/debconf/config.dat
          sudo dpkg --configure -a
          sudo apt update && sudo apt upgrade -y && sudo apt install -y
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo apt update -y && sudo apt install -y
          sudo apt install libgeos++-dev libgeos libgeos-c1v5 libgeos-dev -y
          sudo apt install libgl1 libspatialindex-dev g++ -y
      - name: Install Python packages
        run: |
          pip install -U pip setuptools>=59.5.0 wheel
          pip install numpy>=1.19.0
      - name: Install Geosample
        run: |
          pip install .[tests]
      - name: Unittests
        run: |
          python -m unittest
